general.import = ["/home/redux/.config/alacritty/themes/themes/rose-pine-moon.yaml"]

[cursor]
blink_interval = 300
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 11

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_title = true
opacity = 0.93

[window.dimensions]
columns = 100
lines = 27
